---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/bosh-ecosystem-concourse
    tag: latest

inputs:
- name: bosh-agent

run:
  path: bosh-agent/ci/tasks/test-integration.sh

params:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  JUMPBOX_PRIVATE_KEY:
  JUMPBOX_USERNAME:
  JUMPBOX_IP:
