---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: fhivemind/concourse-dind

inputs:
  - name: bosh-src
  - name: bosh-deployment
  - name: bosh-cli
  - name: bosh-agent

run:
  path: bosh-agent/ci/docker-image/tasks/prepare-container-bosh-docker-build-context.sh

outputs:
  - name: docker-build-context

params:
  container_engine: ~ # docker|garden
