---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "14.04"

inputs:
  - name: bosh-src
  - name: bosh-deployment
  - name: bosh-cli

run:
  path: ci/docker-image/tasks/prepare-container-bosh-docker-build-context.sh

outputs:
  - name: docker-build-context

params:
  container_engine: ~ # docker|garden
